# GitHub Pages 配置
# theme: jekyll-theme-minimal  # 注释掉默认主题，使用自定义layout
title: ChatGPT代充服务 - 5分钟快速充值仅需158元 | 野卡跑路最佳替代
description: 野卡WildCard跑路后的最佳ChatGPT代充方案。支持支付宝微信，5分钟快速充值ChatGPT Plus，仅需158元/月，比市场价便宜10元。10万+野卡用户的选择，iOS官方充值渠道。
baseurl: "/Fast-GPT-Plus"  # GitHub仓库名
url: "https://threezhang.github.io"  # GitHub Pages URL
show_downloads: false
google_analytics: # 添加您的Google Analytics ID

# 插件
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO优化
tagline: 野卡跑路后最佳ChatGPT代充服务 - 仅需158元/月
keywords: "ChatGPT代充,ChatGPT代充服务,野卡跑路,wildcard跑路,ChatGPT Plus充值,ChatGPT充值158元,bewildcard替代,野卡替代方案,ChatGPT支付宝充值,ChatGPT微信充值,ChatGPT Plus 5分钟充值,野卡跑路怎么办"
lang: zh-CN
author:
  name: Fast-GPT-Plus Team
  email: support@fastgptplus.com
  url: https://fastgptplus.com

# 社交链接
social:
  name: Fast-GPT-Plus
  links:
    - https://github.com/threezhang/Fast-GPT-Plus
    - https://fastgptplus.com

# Twitter
twitter:
  username: fastgptplus
  card: summary_large_image

# Logo
logo: /Fast-GPT-Plus/assets/images/logo.png

# 默认值
defaults:
  - scope:
      path: ""
    values:
      image: /Fast-GPT-Plus/assets/images/og-image.png

# 导航菜单
navigation:
  - title: ChatGPT代充教程
    url: /quick-start/
  - title: 野卡跑路替代方案
    url: /docs/bewildcard-alternative/
  - title: 代充常见问题
    url: /faq/

# URL设置
permalink: pretty

# 包含文件夹
include:
  - _layouts
  - docs